language: cpp

dist: trusty
sudo: required

git:
  depth: 10

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
    - os: linux
      dist: trusty

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x ./util/osx/prepare.sh & ./util/osx/prepare.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x ./util/ubuntu/prepare.sh & sudo ./util/ubuntu/prepare.sh; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x ./util/osx/build.sh & ./util/osx/build.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x ./util/ubuntu/build.sh & ./util/ubuntu/build.sh; fi

deploy:
  - provider: releases
    api_key:
      secure: "EFQ4H7PyZdzPVM8AR/iQS9lXYuRMcGVfyQKngD/xj3dHMsnWCRT1+b1QPCsNo2HmS1ADAJf6Yxmt9lc/iRsll17cz64LjfRgFHXWIBJ83aAfbO3PYeyqaW5bJHSs73nC6mJOYpj85VXStU2pMbqPer0OULTNVIOpsGbyn8bjchcCt+L0kh3d9pVnOOCkszvC/SUGtG8g7sqggP6FuRQmFnQiERkEe+Hkaa1AVkAgitOhasugl++HUkW+5jx2qO5htBvOxA0Ve5ScKpZJp/g16P8R97khLYEpBfwwOwoIoE1aMYp9IplgiQpGKmoS/Xt6y3aEFjcYcyOO9FGV8cbhnrSGnL6VK0QB5nJYhzdxIVH1W7bE3VPC1SRgBlzKIJfnf5NwDL9MzScfeRjtbYyS5iv+JMXx3VjbYWt9ilahy2T9UqKz6pMtItL4L3SoUQEJQ4MObbnjeIn1cv65IFW63ZfYHOEXFnOnTZ+L01Y1n2WEDs0J/8+qU79aN/ZxLNR/Nh9Sr6uwkeGYUuXA+OZqL6CYoINQ4Ca2n4G09OeIvyJDghfNXDEm1K4chRDEeMG4hURsKj2qfb/denVnf/lBQx9mL5JUUKJWf5QGv2DJxy1Y5gyY4z+Bpj389Pjvpy19beipraxnngN+jI24Pa0X8x/OujzjppVEILyna/t5MBQ="
    file_glob: true
    file: "QtcCppcheck-*.tar.gz"
    skip_cleanup: true
    on:
      tags: true

notifications:
  email:
    on_success: change
    on_failure: change
